[package]
name = "csv2md"
version = "0.1.0"
edition = "2018"
authors = ["Maxime Bouillot"]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[dependencies]
clap = { version = "3.0.0", features = ["derive"] }

