[package]
name = "csv2md"
version = "0.1.0"
edition = "2018"
authors = ["Maxime Bouillot"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0.0", features = ["derive"] }

